---
title: "CV"
---

### Short Bio
Fumi Miura is a Senior researcher at the National Institute for Public Health and the Environment (RIVM) in the Netherlands and is jointly affiliated with Nagasaki University in Japan. His research focuses on infectious disease modelling, with particular emphasis on transmission heterogeneity, contact networks, and the use of epidemiological and alternative non-epidemiological data to inform targeted intervention strategies. 

### Full CV
- [Download CV (PDF)](files/CV.pdf)

### Positions
- 2023 - Present: Senior researcher
  - Center for Infectious Disease Control, The National Institute for Public Health and the Environment (RIVM), The Netherlands (with Prof. Jacco Wallinga)
    - [Unit for infectious disease modelling](https://www.rivm.nl/en/modelling-infectious-diseases)
- 2020 - 2023: Postdoctoral Research Fellow (funded by JSPS Postdoctoral Research Fellow SPD/CPD)
  - Center for Infectious Disease Control, The National Institute for Public Health and the Environment (RIVM), The Netherlands (with Prof. Jacco Wallinga)
  - Center for Marine Environmental Studies (CMES), Ehime University, Japan (with Prof. Kozo Watanabe)
- 2017 - 2020: Doctoral Research Fellow (funded by JSPS Doctoral Research Fellow DC1)
  - University of Tokyo, Graduate School of Engineering (with Prof. Kensuke Fukushi)
- 2016 - 2017: Visiting researcher
  - Hokkaido University, Graduate School of Medicine (with Prof. Hiroshi Nishiura)
- 2016: Internship researcher
  - World Health Organization (Geneva)
  - Water, Sanitation, Hygiene and Health, Department of Public Health, Social and Environmental Determinants of Health
- 2015 - 2016: Adjunct Research Fellow
  - Research Institute of Capital Formation, Development bank of Japan 

### Education
- Ph.D (Engineering), University of Tokyo, 2017 - 2020
- M.S. (Urban Engineering), University of Tokyo, 2014 - 2017
- B.S. (Urban Engineering), University of Tokyo, 2010 - 2014
